version: '3.9'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  next-app:
    build: 
      context: src/client-side/
      # dockerfile: Dockerfile.next
    env_file:
      - .env
    ports:
      - 3030:3030
    volumes:
      - ./src/client-side/app/app:/app/app
      - ./src/client-side/app/lib:/app/lib
      - file_storage:/app/public/avatar

  nest-app:
    build: 
      context: src/server-side/
      # dockerfile: Dockerfile.nest
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src/server-side/app/src:/app/src
      - file_storage:/uploads
    depends_on:
      - db

volumes:
  pgadmin_data:
  file_storage:
    # driver: local
    # name: file_storage
    # driver_opts:
      # o: bind
      # type: none
      # device: ./src/client-side/app/public/avatar
