version: '3.9'

services:

  db:
    image: postgres
    restart: always
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  next-app:
    build: 
      context: src/client-side/
    env_file:
      - .env
    ports:
      - 3030:3030
    volumes:
      - ./src/client-side/app/app:/app/app
      - ./src/client-side/app/lib:/app/lib
      - ./src/client-side/app/components:/app/components
      # - ./src/client-side/app/public/:/app/public/
    depends_on:
      - nest-app

  nest-app:
    build: 
      context: src/server-side/
    env_file:
      - .env
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./src/server-side/app/src:/app/src
      - ./src/client-side/app/public/avatar/:/uploads
    depends_on:
      - db

  nginx:
    build:
      context: src/file-service/
    restart: always
    ports:
      - 10011:10011
    volumes:
      - ./src/file-service/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src/client-side/app/public/avatar/:/usr/share/nginx/uploads
    depends_on:
      - next-app

volumes:
  pgadmin_data:
